### ISSUE TITLE
Add alt text on images

### ISSUE THREAD

**Issue by cinakur** [InteractiveDesignAndDevelopment/student-portal-theming#48]
Home page 
- [ ] Logo

Student Log-in
- [x] Toby
- [ ] Logo

Staff Log-in
- [ ] Logo

**Comment by Sporkyy** [comment]
I think the logos are on a template file. I don't know where that template is.

**Comment by cinakur** [comment]
@Sporkyy did Rob ask you to look into this because I pinged him after spending 30 minutes looking through files lol.

**Comment by Sporkyy** [comment]
No, I just didn't see anything in the files when I was looking for my own purposes.
